### ISSUE TITLE
[Anon] Bug report: Middle_Earth_Strategy_Battle_Game.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#89] opened 2018-11-16 23:29 UTC
**File:** Middle_Earth_Strategy_Battle_Game.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The watchers of karna have to pay 5 points for bows and poison arrows. They should be free.

**Comment by Zhaph** [comment] 2018-11-17 02:04
Closing as a duplicate of #90 (that has the right file).

**Closed by Zhaph** 2018-11-17 02:04 UTC
Labels: bug
