### ISSUE TITLE
[Anon] Bug report: Isengard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#119] opened 2019-02-04 18:59 UTC
**File:** Isengard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Uruk hai scouts have no base warrior points cost. Upgrades all listed correctly.

**Comment by Zhaph** [comment] 2019-02-16 22:46
Resolved in 6001a6b066c73844c576207d8fb118b7a3d6e324

**Closed by Zhaph** 2019-02-16 22:46 UTC

**Comment by Zhaph** [comment] 2019-02-16 23:40
Duplicate of #107
